pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet restore
- script: dotnet build # Include additional options such as --configuration to meet your need
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
- task: PublishBuildArtifacts@1
